hook_add = '''
" Update filetype.
autocmd MyAutoCmd BufWritePost * nested
    \ if &l:filetype ==# '' || exists('b:ftdetect')
    \ |   unlet! b:ftdetect
    \ |   filetype detect
    \ | endif

" Bash
autocmd BufEnter /tmp/bash* setlocal filetype=sh
let g:is_bash = 1

" JavaScript
let g:SimpleJsIndenter_BriefMode = 1
let g:SimpleJsIndenter_CaseIndentLevel = -1

" Markdown
let g:markdown_fenced_languages = [
      \  'coffee',
      \  'css',
      \  'erb=eruby',
      \  'javascript',
      \  'js=javascript',
      \  'json=javascript',
      \  'ruby',
      \  'sass',
      \  'xml',
      \  'vim',
      \]

" Python
let g:python_highlight_all = 1

" Vim
let g:vimsyntax_noerror = 1
let g:vim_indent_cont = 4
let g:vimsyn_folding = 'afPl'

" XML
let g:xml_syntax_folding = 1

" Reload .vimrc automatically.
autocmd MyAutoCmd BufWritePost .vimrc,vimrc,*.rc.vim,*.toml source $MYVIMRC | redraw
'''

[ftplugin]

_ = '''
    if !&l:modifiable
        setlocal nofoldenable
        setlocal foldcolumn=0
        setlocal colorcolumn=
    endif
'''

c = 'setlocal omnifunc='

css = 'setlocal omnifunc=csscomplete#CompleteCSS'

javascript = '''
setlocal softtabstop=2 shiftwidth=2
setlocal tabstop=2 foldmethod=indent
'''

python = '''
setlocal foldmethod=indent
if has('python3')
    setlocal omnifunc=python3complete#Complete
else
    setlocal omnifunc=pythoncomplete#Complete
endif
'''

sql = '''
setlocal omnifunc=sqlcomplete#Complete
nnoremap <leader>xx :execute 'silent %w !sqlformat -r -k upper -i lower -o % %' \| execute ':e!'<CR>
'''

trpy = '''
setlocal syntax=python.trpy
setlocal foldmethod=syntax
'''

html = '''
setlocal omnifunc=htmlcomplete#CompleteTags
setlocal includeexpr=substitute(v:fname,'^\\/','','')
setlocal path+=./;/
'''

markdown = '''
setlocal omnifunc=htmlcomplete#CompleteTags
'''

nim = '''
setlocal foldmethod=indent
setlocal tabstop=2 softtabstop=2 shiftwidth=2
'''

sh = '''
setlocal foldmethod=indent foldlevel=0
setlocal tabstop=4 softtabstop=4 shiftwidth=4
'''

vim = '''
if 5000 < line('$')
  syntax sync minlines=200
endif
setlocal foldmethod=marker
setlocal nomodeline
'''

xml = '''
setlocal omnifunc=xmlcomplete#CompleteTags
setlocal foldmethod=syntax
setlocal foldlevel=2
'''

qfreplace = 'setlocal nofoldenable'

toml = 'syntax sync minlines=500'
