# [[plugins]]
# repo = 'zchee/deoplete-clang'
# on_ft = ['c', 'cpp']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
    let g:deoplete#sources#jedi#show_docstring = 1
    let g:deoplete#sources#jedi#enable_cache = 0
'''

# Tryton
[[plugins]]
on_ft = ['python', 'py', 'xml']
repo = 'JCavallo/tryton-vim'
on_source = 'unite.vim'
hook_add = '''
    let g:tryton_default_mappings = 1
    let g:tryton_trytond_path = "$PROJECT_PATH/trytond"
    let g:tryton_server_host_name = 'localhost'
    let g:tryton_server_port = '7999'
    let g:tryton_server_login = 'admin'
    nmap <leader>com 0yf df oreview http://rietveld.coopengo.com/jkp$xXOjkgg0fFf:lyFFf:lldFFjojkkpxXXX
'''

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = 'javascript'
hook_source = '''
    let g:tern_request_timeout = 1
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
if = "has('nvim')"
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    execute 'source ' . expand($VIM_FOLDER) . '/rc/plugins/deoplete.rc.vim'
'''

# Snippets
[[plugins]]
repo = 'SirVer/ultisnips'
if = "has('nvim')"
on_i = 1
on_source = 'unite.vim'
depends = 'deoplete.nvim'
hook_add = '''
    let g:UltiSnipsExpandTrigger="<tab>"
    let g:UltiSnipsJumpForwardTrigger="<tab>"
    let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
'''
