# =========================================================================== #
# Only vimproc here
# =========================================================================== #

[[plugins]]
repository = 'Shougo/vimproc.vim'
build = 'make'
